### PR TITLE
Improve column renaming for HDB migration 6

### LINKED ISSUE #212: HDB Database has invalid foreign key constrains
When creating a new HDB the database has invalid foreign key relations in them. This currently does not cause any error since foreign keys are apparently not checked, but nevertheless makes editing the DB in tools like SQLiteBrowser harder. (Also it somehow defeats the purpose of having the foreign key relations in the first place).

For example the table `operation_implementation_variable` has the following relation, mentioning the non-existing table `operation_implementation_old`:

```sql
CREATE TABLE "operation_implementation_variable" (
	[...]
	PRIMARY KEY("id"),
	FOREIGN KEY("operation") REFERENCES "operation_implementation_old"("id")
);
```
It is cause the [migration code for version 6](https://github.com/cpc/openasip/blob/main/openasip/src/applibs/hdb/HDBManager.cc#L487):

```cpp
dbConnection_->updateQuery(std::string(
    "ALTER TABLE operation_implementation RENAME TO "
    "operation_implementation_old"));
dbConnection_->updateQuery(std::string(
    "CREATE TABLE operation_implementation ( "
//...
dbConnection_->updateQuery(std::string(
    "INSERT INTO operation_implementation "
        "(id, name, bus_definition, post_op_vhdl, post_op_verilog, "
        "initial_vhdl, initial_verilog) "
    "SELECT id, name, bus_definition, post_op_vhdl, post_op_verilog, "
           "default_vhdl, default_verilog "
    "FROM operation_implementation_old"));
dbConnection_->updateQuery(std::string(
    "DROP TABLE operation_implementation_old"));
```
This renames the existing table (which updates the foreign key relation to the new name) and then creates a new table with the old name, moves all the data and drops the old table. This causes the foreign keys to reference the non-existing old table.

The original intention of the code seems to be to rename a column. According to [this answer](https://stackoverflow.com/questions/805363/how-do-i-rename-a-column-in-a-sqlite-database-table/52346199#52346199) on StackOverflow this is now possible using the `ALTER TABLE` query.

### PR DESCRIPTION
**Pull request by nrother**
Fixes #212 

Note that currently no effort is made to fix old databases which may have invalid foreign keys due to the old code. ALTER TABLE RENAME COLUMN was added in version 3.25.0 of SQLite.

### CODE REVIEW

**Comment by pjaaskel** [comment]
Does it break older than 3.25.0 SQLite versions? At least README.md needs to be updated if so. How old is that version, does the oldest alive Ubuntu LTS ship that already?

**Comment by sarahec** [comment]
Ubuntu 18.04 LTS has MySQL 3.22, see: [package repo search for mySQL](https://packages.ubuntu.com/search?keywords=sqlite3)

**Comment by pjaaskel** [comment]
@sarahec we are using SQLite, not MySQL, those are two different SQL-based RDBMs.

**Comment by nrother** [comment]
I think @sarahec had a typo there, both the version and the package query link refer to SQLite.

**Comment by sarahec** [comment]
Yes, that was a brain slip. It's SQLite 3.22 in Ubuntu 18.04.

**Comment by pjaaskel** [comment]
20.04 has 3.31 so I guess it's fine since it's only a few months until EOL. LGTM.

**Comment by pjaaskel** [comment]
Can you update README.md's SQLite minimum version and CHANGES?

**Comment by nrother** [comment]
Updated the files. I'm not so sure about the minimum version if RHEL that is required now, they don't seem to have public information about their packages.

**Pull request merged**
