### PR TITLE
.gitignore cleanup

### PR DESCRIPTION
**Pull request by sarahec**
oacc-riscv is showing up in the Git changes after a build. This patch adds the built file to the .gitignore.

### CODE REVIEW

**Comment by sarahec** [comment]
Would it make sense to sort the .gitignore? I'm happy to make that change.

**Comment by pjaaskel** [comment]
Sure, thanks!

**Comment by sarahec** [comment]
Sorted. I see additional places we need to clean up, but I also need to ask some questions (for example: do we ever want to keep the Makefile when a Makefile.in is present?)

Maybe merge this one and I'll start a thread for the cleanup project and its questions?

**Comment by pjaaskel** [comment]
Thanks for your cleanup efforts! You can check if we need the Makefile (I think not, but I'm not sure of Newlib) is needed if it's checked in to git.

**Comment by sarahec** [comment]
Done. Needed Makefiles remain checked in, makefiles generated during the build (and removed with distclean) are excluded. 

Let's push it from here.

**Pull request merged**
